### PR TITLE
Add FileResult interface

### PR DESCRIPTION
**Pull request by nategbrown9**

### CODE REVIEW

**Review by syoung-smallwisdom — COMMENTED** [review]
Not sure how you are using these but if you compare it to `JsonModel.ResultModel` your archiving needs to be able to find the file and that is *not* the relativePath.

Instead, the relativePath is serialized but the full path (which may include DeviceID on iPhones) is not. (I guess technically speaking file path is now sandboxed but the encoding does differentiate between "relativePath" which is used name the file in the file archive and "url" which points at the file on disk.

WRT the `JsonFileArchivableResult`, I'm also not sure what that one is suppose to be.

I'm guessing maybe the equivalent to:

```
/// An archivable result is an object wrapper for results that allows them to be transformed into
/// data for a zipped archive or service.
public protocol FileArchivable {
    
    /// Build the archiveable or uploadable data for this result.
    func buildArchivableFileData(at stepPath: String?) throws -> (fileInfo: FileInfo, data: Data)?
}
```

Which *could* be a fine way to handle, but does mean that you may run into problems with the encoding if there is a filename conflict b/c the files are in a section? Guess it depends upon how you are handling that. 

FWIW, most of the weirdness of the existing protocol (on iOS) is b/c it was written to support ResearchKit model objects which are super bizarre and to support image/sound that may not be written to a temp file. ¯\_(ツ)_/¯

**Comment by nategbrown9** [comment]
I will change relativePath to just path to match File.path, which is where the value is coming from. It is the path to access the file that is to be included in the archive.  The archiving/zipping code we are currently using from [BridgeDataUploadUtils](https://github.com/Sage-Bionetworks/BridgeDataUploadUtils) only supports a flat file structure, so it just uses File.filename when building the archive.

`JsonFileArchivableResult` is meant to be equivalent to `FileArchivable`, seems like our current use-cases are all JSON so I just worried about that for now. Here is how I see it being used in the context of tapping results:
```
@Serializable
@SerialName("tapping")
data class TappingResultObject(
    override val identifier: String,
    override var startDateTime: Instant = Clock.System.now(),
    override var endDateTime: Instant? = null,
    var hand: String? = null,
    var samples: List<TappingSampleObject> = mutableListOf(),
    var tapCount: Int = 0
) : JsonFileArchivableResult {
    override fun copyResult(identifier: String): TappingResultObject {
        return this.copy(identifier = identifier, samples = this.samples.map { it.copy() })
    }

    @Transient
    override val filename: String
        get() = hand + "_" + identifier
    @Transient
    override val json: String
        get() = Json.encodeToString(this)
    override val jsonSchema: String?
        get() = "https://github.com/Sage-Bionetworks/mobile-client-json/blob/main/schemas/v1/TappingResultObject.json"
}
```

**Comment by syoung-smallwisdom** [comment]
How does your result know the "section" name in order to append it to the file name? Do you have confidence that future uses of repeating sections will always include the section name?

Also, every time you call `json` you are running a method. With 200 tap samples, on an older phone, this can take actual time to serialize (which is why archiving runs on a background thread). I know that Kotlin **allows** this kind of thing, but should it be obfuscated this way?

Example iOS implementation:

```
extension TappingResultObject : FileArchivable {
    
    public func buildArchivableFileData(at stepPath: String?) throws -> (fileInfo: FileInfo, data: Data)? {
        let data = try self.jsonEncodedData()
        return (fileInfo(stepPath), data)
    }
    
    private func fileInfo(_ stepPath: String?) -> FileInfo {
        
        // The filename should include the section (left/right).
        let whichHand = hand ?? stepPath?.components(separatedBy: "/").compactMap { HandSelection(rawValue: $0) }.first
        let filename = whichHand.map { "\($0.rawValue)_\(identifier)" } ?? identifier
        
        return .init(filename: filename,
                     timestamp: startDate,
                     contentType: "application/json",
                     identifier: identifier,
                     stepPath: stepPath,
                     jsonSchema: jsonSchema)
    }
}
```

**Review by syoung-smallwisdom — APPROVED** [review]
looks good

**Pull request merged**
